#!/usr/bin/bash
echo "Playing with colors"
echo "====================="
echo -e "\e[31mHello In RED\e[0m"
echo -e "\e[32mHello In GREEN\e[0m"
echo -e "\e[33mHello In YELLOW\e[0m"
echo -e "\e[34mHello In BLUEe[0m"
echo -e "\e[35mHello In MAGENTA\e[0m"
echo -e "\e[36mHello In CYAN\e[0m"
echo "===================="
